{% set name = "schemdraw" %}
{% set version = "0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/schemdraw-{{ version }}.tar.gz
  sha256: 908689bd4cfa2c19de2b4c94908ed98f3bd6d114ec39bd79349e71a6ce98128f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - typing-extensions

test:
  imports:
    - schemdraw
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://schemdraw.readthedocs.io/
  summary: Electrical circuit schematic drawing
  dev_url: https://bitbucket.org/cdelker/schemdraw
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - dkozel
