{% set name = "schemdraw" %}
{% set version = "0.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/schemdraw-{{ version }}.tar.gz
  sha256: 6127b28d8fe0a8c78d37aa2dff93c1d39f18da84e59172f865b8fbd7664af386

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - typing-extensions

test:
  imports:
    - schemdraw
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://schemdraw.readthedocs.io/
  summary: Electrical circuit schematic drawing
  dev_url: https://bitbucket.org/cdelker/schemdraw
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - dkozel
