{% set name = "schemdraw" %}
{% set version = "0.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/schemdraw-{{ version }}.tar.gz
  sha256: 59d1fcfe817f93f8bfc37a3f4645186dc03316bbcfd9ac68804fd6cb3aa69f51

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - typing-extensions

test:
  imports:
    - schemdraw
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://schemdraw.readthedocs.io/
  summary: Electrical circuit schematic drawing
  dev_url: https://bitbucket.org/cdelker/schemdraw
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - dkozel
